name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci --prefer-offline --no-audit

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Verify Next.js configuration
        run: |
          echo "Checking Next.js config..."
          cat next.config.ts
          echo "Checking package.json scripts..."
          cat package.json | grep -A 10 '"scripts"'

      - name: Build Next.js app
        run: |
          echo "Starting Next.js build..."
          npm run build:static
          echo "Build completed. Checking output directory..."
          ls -la
          if [ -d "dist" ]; then
            echo "✅ dist directory exists"
            ls -la dist/ | head -20
            echo "Total files in dist:"
            find dist -type f | wc -l
          else
            echo "❌ dist directory not found"
            echo "Available directories:"
            ls -la | grep -E "^d"
            exit 1
          fi
        env:
          NODE_ENV: production
          GITHUB_PAGES: true
          NEXT_PUBLIC_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_GRAPHQL_URL || 'http://localhost:4000/graphql' }}

      - name: Add .nojekyll file
        run: |
          touch dist/.nojekyll
          echo "Added .nojekyll file to dist directory"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: github-pages
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
